// <auto-generated />
using System;
using AlphaX.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AlphaX.Migrations
{
    [DbContext(typeof(AlphaXContext))]
    [Migration("20260313035257_UpdateModelsForPostgreSQL")]
    partial class UpdateModelsForPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AlphaX.Models.ComplianceFinding", b =>
                {
                    b.Property<string>("FindingId")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remediation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FindingId");

                    b.HasIndex("ScanId");

                    b.ToTable("ComplianceFindings");
                });

            modelBuilder.Entity("AlphaX.Models.Endpoint", b =>
                {
                    b.Property<string>("EndpointId")
                        .HasColumnType("text");

                    b.Property<string>("AgentVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EndpointId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("AlphaX.Models.EndpointInfo", b =>
                {
                    b.Property<string>("EndpointInfoId")
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastBootTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OSBuildNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessorInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanResultScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalMemory")
                        .HasColumnType("bigint");

                    b.HasKey("EndpointInfoId");

                    b.HasIndex("ScanId")
                        .IsUnique();

                    b.HasIndex("ScanResultScanId");

                    b.ToTable("EndpointInfos");
                });

            modelBuilder.Entity("AlphaX.Models.InstalledSoftware", b =>
                {
                    b.Property<string>("SoftwareId")
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointInfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstalledSoftwareId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SoftwareId");

                    b.HasIndex("EndpointInfoId");

                    b.ToTable("InstalledSoftware");
                });

            modelBuilder.Entity("AlphaX.Models.MaintenanceFinding", b =>
                {
                    b.Property<string>("FindingId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FindingId");

                    b.ToTable("MaintenanceFindings");
                });

            modelBuilder.Entity("AlphaX.Models.NetworkInterface", b =>
                {
                    b.Property<string>("NetworkInterfaceId")
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointInfoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddresses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NetworkInterfaceId");

                    b.HasIndex("EndpointInfoId");

                    b.ToTable("NetworkInterfaces");
                });

            modelBuilder.Entity("AlphaX.Models.Scan", b =>
                {
                    b.Property<string>("ScanId")
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FindingsCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScanEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScanStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScanId");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("AlphaX.Models.ScanResult", b =>
                {
                    b.Property<string>("ScanId")
                        .HasColumnType("text");

                    b.Property<double>("ComplianceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedChecks")
                        .HasColumnType("integer");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OverallStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PassedChecks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScanEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScanStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ScanStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalChecks")
                        .HasColumnType("integer");

                    b.Property<int>("WarningChecks")
                        .HasColumnType("integer");

                    b.HasKey("ScanId");

                    b.HasIndex("EndpointId");

                    b.ToTable("ScanResults");
                });

            modelBuilder.Entity("AlphaX.Models.SecurityFinding", b =>
                {
                    b.Property<string>("FindingId")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FindingId");

                    b.ToTable("SecurityFindings");
                });

            modelBuilder.Entity("AlphaX.Models.ServiceFinding", b =>
                {
                    b.Property<string>("FindingId")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FoundDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remediation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ScanId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FindingId");

                    b.ToTable("ServiceFindings");
                });

            modelBuilder.Entity("AlphaX.Models.ComplianceFinding", b =>
                {
                    b.HasOne("AlphaX.Models.ScanResult", "ScanResult")
                        .WithMany("Findings")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanResult");
                });

            modelBuilder.Entity("AlphaX.Models.EndpointInfo", b =>
                {
                    b.HasOne("AlphaX.Models.ScanResult", null)
                        .WithOne("EndpointInfo")
                        .HasForeignKey("AlphaX.Models.EndpointInfo", "ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlphaX.Models.ScanResult", "ScanResult")
                        .WithMany()
                        .HasForeignKey("ScanResultScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanResult");
                });

            modelBuilder.Entity("AlphaX.Models.InstalledSoftware", b =>
                {
                    b.HasOne("AlphaX.Models.EndpointInfo", "EndpointInfo")
                        .WithMany("InstalledSoftware")
                        .HasForeignKey("EndpointInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndpointInfo");
                });

            modelBuilder.Entity("AlphaX.Models.NetworkInterface", b =>
                {
                    b.HasOne("AlphaX.Models.EndpointInfo", "EndpointInfo")
                        .WithMany("NetworkInterfaces")
                        .HasForeignKey("EndpointInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EndpointInfo");
                });

            modelBuilder.Entity("AlphaX.Models.ScanResult", b =>
                {
                    b.HasOne("AlphaX.Models.Endpoint", null)
                        .WithMany("ScanResults")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlphaX.Models.Endpoint", b =>
                {
                    b.Navigation("ScanResults");
                });

            modelBuilder.Entity("AlphaX.Models.EndpointInfo", b =>
                {
                    b.Navigation("InstalledSoftware");

                    b.Navigation("NetworkInterfaces");
                });

            modelBuilder.Entity("AlphaX.Models.ScanResult", b =>
                {
                    b.Navigation("EndpointInfo")
                        .IsRequired();

                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
